name: Sonar Cloud

on:
    push:
        branches:
            - main
    pull_request:
        types: [ opened, synchronize, reopened ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    REMOTE_DOCKER_URI: ${{ secrets.REMOTE_DOCKER_URI }}

jobs:
    sonarcloud:
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: ardoco/actions/.github/workflows/sonarcloud.yml@main
        with:
            with-submodules: true
            runs-on: ubuntu-latest
        secrets:
            SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

