name: Maven Verify

on:
    push: # Ignore releases and main dev branch
        tags-ignore:
            - 'v*'
        branches-ignore:
            - 'main'
    pull_request:
        types: [ opened, synchronize, reopened ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    REMOTE_DOCKER_URI: ${{ secrets.REMOTE_DOCKER_URI }}

jobs:
    verify:
        uses: ardoco/actions/.github/workflows/maven.yml@main
        with:
            deploy: false
            with-submodules: true
            runs-on: ubuntu-latest
        secrets:
            OSSRH_USER: ""
            OSSRH_TOKEN: ""
            GPG_KEY: ""

